/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.cinvir.datascience;

/**
 *
 * @author cvrodriguez
 */
public class ApreciasionMain extends javax.swing.JFrame {

    /**
     * Creates new form Nuevo
     */
    public ApreciasionMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jComboBox6 = new javax.swing.JComboBox<>();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jlabelApreciacionporlosHijos = new javax.swing.JLabel();
        jlabelRazonDeAborto = new javax.swing.JLabel();
        jLabeldefecbeb = new javax.swing.JLabel();
        jLabelNoMHijos = new javax.swing.JLabel();
        jLabelMuerteMadre = new javax.swing.JLabel();
        jLabelBaIngreso = new javax.swing.JLabel();
        jLabelViolacion = new javax.swing.JLabel();
        jLabelNoCasada = new javax.swing.JLabel();
        jLabelMuerQuiere = new javax.swing.JLabel();
        jLabelEstCivil = new javax.swing.JLabel();
        jLabelNumHijos = new javax.swing.JLabel();
        jLabelRelig = new javax.swing.JLabel();
        jLabelHijAdultCasa = new javax.swing.JLabel();
        cbxdefBe = new javax.swing.JComboBox<>();
        cbxNoMasHijo = new javax.swing.JComboBox<>();
        cbxMuerMam = new javax.swing.JComboBox<>();
        cbxBaIngre = new javax.swing.JComboBox<>();
        cbxVioala = new javax.swing.JComboBox<>();
        cbxNoCasadaNoquiere = new javax.swing.JComboBox<>();
        cbxsiQuiereMujer = new javax.swing.JComboBox<>();
        cbxEstadoCivil = new javax.swing.JComboBox<>();
        cbxNumHijos = new javax.swing.JComboBox<>();
        cbxRel = new javax.swing.JComboBox<>();
        cbxHijAdultLikeHose = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        ApreciacionporelTrabajo = new javax.swing.JLabel();
        jLabelimportantrabajo = new javax.swing.JLabel();
        jLabelricoNotraba = new javax.swing.JLabel();
        jLabellastyeartiempoCompl = new javax.swing.JLabel();
        jLabelEnqueTrabaj = new javax.swing.JLabel();
        jLabelParaQuiTrA = new javax.swing.JLabel();
        jLabelgENERO = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        cbxSuerOayuda = new javax.swing.JComboBox<>();
        cbxContraba = new javax.swing.JComboBox<>();
        cbxTiempoCompl = new javax.swing.JComboBox<>();
        cbxColegi = new javax.swing.JComboBox<>();
        cbxAlgiMas = new javax.swing.JComboBox<>();
        cbxSexo = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        ApreciacionporelTrabajo1 = new javax.swing.JLabel();
        jLabelSexoFueraMatr = new javax.swing.JLabel();
        jLabelRelaHomose = new javax.swing.JLabel();
        jLabelRelacionesFueraMatr = new javax.swing.JLabel();
        jLabelCasadoViduo = new javax.swing.JLabel();
        jLabelViudoAlgVez = new javax.swing.JLabel();
        jLabelFelGene = new javax.swing.JLabel();
        cbxSeFueMatri = new javax.swing.JComboBox<>();
        cbxSexoHomos = new javax.swing.JComboBox<>();
        cbxRelacionFueraMatri = new javax.swing.JComboBox<>();
        cbxCasaDivor = new javax.swing.JComboBox<>();
        cbxViudo = new javax.swing.JComboBox<>();
        cbxFelic = new javax.swing.JComboBox<>();
        btnFelicid = new javax.swing.JButton();
        jLabelResult = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "No Sabe", "No responde" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlabelApreciacionporlosHijos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlabelApreciacionporlosHijos.setText("Apreciaciòn por los Hijos");

        jlabelRazonDeAborto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlabelRazonDeAborto.setText("Razones del aborto");

        jLabeldefecbeb.setText("Defectos del bebe");

        jLabelNoMHijos.setText("No mas hijos");

        jLabelMuerteMadre.setText("Riesgo de vida de la madre");

        jLabelBaIngreso.setText("Bajos ingresos");

        jLabelViolacion.setText("violaciòn");

        jLabelNoCasada.setText("No casada  no quiere casarse");

        jLabelMuerQuiere.setText("Si la mujer quiere");

        jLabelEstCivil.setText("Estado civil");

        jLabelNumHijos.setText("Numero de hijos");

        jLabelRelig.setText("Religion");

        jLabelHijAdultCasa.setText("Hijos Adult viviendo en casa");

        cbxdefBe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "No Sabe", "No responde" }));
        cbxdefBe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxdefBeActionPerformed(evt);
            }
        });

        cbxNoMasHijo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "No Sabe", "No responde" }));
        cbxNoMasHijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNoMasHijoActionPerformed(evt);
            }
        });

        cbxMuerMam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "No Sabe", "No responde" }));
        cbxMuerMam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMuerMamActionPerformed(evt);
            }
        });

        cbxBaIngre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "No Sabe", "No responde" }));
        cbxBaIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBaIngreActionPerformed(evt);
            }
        });

        cbxVioala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "No Sabe", "No responde" }));
        cbxVioala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxVioalaActionPerformed(evt);
            }
        });

        cbxNoCasadaNoquiere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "No Sabe", "No responde" }));
        cbxNoCasadaNoquiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNoCasadaNoquiereActionPerformed(evt);
            }
        });

        cbxsiQuiereMujer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "No Sabe", "No responde" }));
        cbxsiQuiereMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxsiQuiereMujerActionPerformed(evt);
            }
        });

        cbxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nunca se caso", "Viudo", "Divorciado", "Separado", "Casado", "No responde" }));
        cbxEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoCivilActionPerformed(evt);
            }
        });

        cbxNumHijos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "Mas", "No sabe ", "No responde" }));
        cbxNumHijos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNumHijosActionPerformed(evt);
            }
        });

        cbxRel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Protestante", "Catolico", "Judio", "Ninguno", "Otro", "No responde", "No sabe", "Orthodox-Cristiano", "Cristiano", "Moslem/islam", "Inter-nondenomitiol", "Budismo", "Hinduismo", "tivo americano", "Otros orientales" }));
        cbxRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRelActionPerformed(evt);
            }
        });

        cbxHijAdultLikeHose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Una buena idea", "Una mala idea", "Depende", "NA", "No responde", "No sabe" }));
        cbxHijAdultLikeHose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxHijAdultLikeHoseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMuerteMadre)
                            .addComponent(jLabelNoMHijos)
                            .addComponent(jLabelMuerQuiere)
                            .addComponent(jLabelNoCasada)
                            .addComponent(jLabelViolacion)
                            .addComponent(jLabelBaIngreso)
                            .addComponent(jlabelRazonDeAborto)
                            .addComponent(jLabeldefecbeb))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxNoCasadaNoquiere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxsiQuiereMujer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbxNoMasHijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxdefBe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxMuerMam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxBaIngre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxVioala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelNumHijos)
                                            .addComponent(jLabelEstCivil)
                                            .addComponent(jLabelRelig))
                                        .addGap(75, 75, 75))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelHijAdultCasa)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxNumHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxRel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxHijAdultLikeHose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jlabelApreciacionporlosHijos)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jlabelApreciacionporlosHijos)
                .addGap(39, 39, 39)
                .addComponent(jlabelRazonDeAborto)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelViolacion)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabeldefecbeb)
                                        .addComponent(cbxdefBe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelNoMHijos)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbxNoMasHijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelNumHijos)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabelMuerteMadre)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabelBaIngreso))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(cbxMuerMam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cbxBaIngre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jLabelEstCivil))
                            .addGap(18, 18, 18)
                            .addComponent(cbxVioala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxNumHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxRel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRelig))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxHijAdultLikeHose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHijAdultCasa))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNoCasada, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(cbxNoCasadaNoquiere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMuerQuiere)
                    .addComponent(cbxsiQuiereMujer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );

        jTabbedPane2.addTab("Hijos", jPanel1);

        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ApreciacionporelTrabajo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ApreciacionporelTrabajo.setText("Apreciaciòn por el trabajo");

        jLabelimportantrabajo.setText("Que es mas importante en el trabajo");

        jLabelricoNotraba.setText("Si es rico seguria trabajando");

        jLabellastyeartiempoCompl.setText("El año pasado trabajo tiempo completo o parcial");

        jLabelEnqueTrabaj.setText("En que trabaja");

        jLabelParaQuiTrA.setText("Para quien trabaja");

        jLabelgENERO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelgENERO.setText("Genero");

        jLabelSexo.setText("Sexo");

        cbxSuerOayuda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suerte o ayuda", "Trabajo duro", "Ambos igualmente", "No sabe", "No responde", "NA" }));
        cbxSuerOayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSuerOayudaActionPerformed(evt);
            }
        });

        cbxContraba.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Continua trabajando", "Para de trabajar", "No sabe", "No responde", "NA" }));
        cbxContraba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxContrabaActionPerformed(evt);
            }
        });

        cbxTiempoCompl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiempo completo", "Tiempo parcial", "No responde", "No sabe", "NA" }));
        cbxTiempoCompl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTiempoComplActionPerformed(evt);
            }
        });

        cbxColegi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colegio ", "Manteniendo la casa", "Retirado", "Trabajo a tiempo completo", "Trabajo a tiempo parcial", "Despedido", "trabajador interino no funciomiento", "No responde", "Otro" }));
        cbxColegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxColegiActionPerformed(evt);
            }
        });

        cbxAlgiMas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alguien mas", "Por cuanta propia", "No responde", "No sabe", "NA" }));
        cbxAlgiMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAlgiMasActionPerformed(evt);
            }
        });

        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));
        cbxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSexoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(ApreciacionporelTrabajo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabellastyeartiempoCompl)
                            .addComponent(jLabelimportantrabajo)
                            .addComponent(jLabelricoNotraba)
                            .addComponent(jLabelSexo)
                            .addComponent(jLabelParaQuiTrA)
                            .addComponent(jLabelEnqueTrabaj)
                            .addComponent(jLabelgENERO))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxSuerOayuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxContraba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTiempoCompl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxAlgiMas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxColegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(ApreciacionporelTrabajo)
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxSuerOayuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelimportantrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxContraba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelricoNotraba))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabellastyeartiempoCompl)
                    .addComponent(cbxTiempoCompl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEnqueTrabaj)
                    .addComponent(cbxColegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxAlgiMas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelParaQuiTrA))
                .addGap(28, 28, 28)
                .addComponent(jLabelgENERO)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSexo))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Trabajo", jPanel2);

        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ApreciacionporelTrabajo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ApreciacionporelTrabajo1.setText("Apreciaciòn sobre el matrimonio");

        jLabelSexoFueraMatr.setText("Que piensa del sexo fuera del matrimonio estando casada ");

        jLabelRelaHomose.setText("Que piensa de las relacion sexual homosexuales");

        jLabelRelacionesFueraMatr.setText(" Tuvorelaciones con otro estando casado");

        jLabelCasadoViduo.setText("Si esta caso o viudo Alguna vez se ha separado");

        jLabelViudoAlgVez.setText("Alguna vez fue viudo");

        jLabelFelGene.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFelGene.setText("Felicidad en general");

        cbxSeFueMatri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Siempre es malo", "Casi siempre es malo", "No esta mal en absoluto", "A veces es malo", "No sabe", "No responde", "NA" }));
        cbxSeFueMatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSeFueMatriActionPerformed(evt);
            }
        });

        cbxSexoHomos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Siempre es malo", "Casi siempre es malo", "No esta mal en absoluto", "A veces es malo", "No sabe", "No responde", "NA" }));
        cbxSexoHomos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSexoHomosActionPerformed(evt);
            }
        });

        cbxRelacionFueraMatri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nunca se caso", "No", "Si", "No responde", "No sabe", "NA" }));
        cbxRelacionFueraMatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRelacionFueraMatriActionPerformed(evt);
            }
        });

        cbxCasaDivor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "No Sabe", "No responde" }));
        cbxCasaDivor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCasaDivorActionPerformed(evt);
            }
        });

        cbxViudo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", "No Sabe", "No responde" }));
        cbxViudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxViudoActionPerformed(evt);
            }
        });

        cbxFelic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bastante feliz", "No muy feliz", "Muy feliz", "No responde", "No sabe", " " }));
        cbxFelic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFelicActionPerformed(evt);
            }
        });

        btnFelicid.setText("Calcular");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(211, 211, 211)
                            .addComponent(btnFelicid)
                            .addGap(36, 36, 36)
                            .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(235, 235, 235)
                            .addComponent(ApreciacionporelTrabajo1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRelacionesFueraMatr)
                            .addComponent(jLabelSexoFueraMatr)
                            .addComponent(jLabelRelaHomose)
                            .addComponent(jLabelCasadoViduo)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelFelGene, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelViudoAlgVez, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxFelic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxSeFueMatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxSexoHomos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxRelacionFueraMatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxViudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCasaDivor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(ApreciacionporelTrabajo1)
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbxSeFueMatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxSexoHomos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxRelacionFueraMatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(cbxCasaDivor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxViudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxFelic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFelGene)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelSexoFueraMatr)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelRelaHomose)
                        .addGap(23, 23, 23)
                        .addComponent(jLabelRelacionesFueraMatr)
                        .addGap(22, 22, 22)
                        .addComponent(jLabelCasadoViduo)
                        .addGap(28, 28, 28)
                        .addComponent(jLabelViudoAlgVez)))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnFelicid)
                        .addGap(35, 35, 35)))
                .addGap(28, 28, 28))
        );

        jTabbedPane2.addTab("Matrimonio", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTabbedPane2)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Aborto");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void cbxSuerOayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSuerOayudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSuerOayudaActionPerformed

    private void cbxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSexoActionPerformed

    private void cbxAlgiMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAlgiMasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAlgiMasActionPerformed

    private void cbxColegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxColegiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxColegiActionPerformed

    private void cbxTiempoComplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTiempoComplActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTiempoComplActionPerformed

    private void cbxContrabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxContrabaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxContrabaActionPerformed

    private void cbxSexoHomosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSexoHomosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSexoHomosActionPerformed

    private void cbxRelacionFueraMatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRelacionFueraMatriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRelacionFueraMatriActionPerformed

    private void cbxCasaDivorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCasaDivorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCasaDivorActionPerformed

    private void cbxViudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxViudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxViudoActionPerformed

    private void cbxFelicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFelicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxFelicActionPerformed

    private void cbxSeFueMatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSeFueMatriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSeFueMatriActionPerformed

    private void cbxHijAdultLikeHoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxHijAdultLikeHoseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxHijAdultLikeHoseActionPerformed

    private void cbxRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRelActionPerformed

    private void cbxsiQuiereMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxsiQuiereMujerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxsiQuiereMujerActionPerformed

    private void cbxNumHijosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNumHijosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNumHijosActionPerformed

    private void cbxEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEstadoCivilActionPerformed

    private void cbxNoCasadaNoquiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNoCasadaNoquiereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNoCasadaNoquiereActionPerformed

    private void cbxVioalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxVioalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxVioalaActionPerformed

    private void cbxBaIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBaIngreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxBaIngreActionPerformed

    private void cbxMuerMamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMuerMamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMuerMamActionPerformed

    private void cbxNoMasHijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNoMasHijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNoMasHijoActionPerformed

    private void cbxdefBeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxdefBeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxdefBeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApreciasionMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApreciasionMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApreciasionMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApreciasionMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApreciasionMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApreciacionporelTrabajo;
    private javax.swing.JLabel ApreciacionporelTrabajo1;
    private javax.swing.JButton btnFelicid;
    private javax.swing.JComboBox<String> cbxAlgiMas;
    private javax.swing.JComboBox<String> cbxBaIngre;
    private javax.swing.JComboBox<String> cbxCasaDivor;
    private javax.swing.JComboBox<String> cbxColegi;
    private javax.swing.JComboBox<String> cbxContraba;
    private javax.swing.JComboBox<String> cbxEstadoCivil;
    private javax.swing.JComboBox<String> cbxFelic;
    private javax.swing.JComboBox<String> cbxHijAdultLikeHose;
    private javax.swing.JComboBox<String> cbxMuerMam;
    private javax.swing.JComboBox<String> cbxNoCasadaNoquiere;
    private javax.swing.JComboBox<String> cbxNoMasHijo;
    private javax.swing.JComboBox<String> cbxNumHijos;
    private javax.swing.JComboBox<String> cbxRel;
    private javax.swing.JComboBox<String> cbxRelacionFueraMatri;
    private javax.swing.JComboBox<String> cbxSeFueMatri;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JComboBox<String> cbxSexoHomos;
    private javax.swing.JComboBox<String> cbxSuerOayuda;
    private javax.swing.JComboBox<String> cbxTiempoCompl;
    private javax.swing.JComboBox<String> cbxVioala;
    private javax.swing.JComboBox<String> cbxViudo;
    private javax.swing.JComboBox<String> cbxdefBe;
    private javax.swing.JComboBox<String> cbxsiQuiereMujer;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabelBaIngreso;
    private javax.swing.JLabel jLabelCasadoViduo;
    private javax.swing.JLabel jLabelEnqueTrabaj;
    private javax.swing.JLabel jLabelEstCivil;
    private javax.swing.JLabel jLabelFelGene;
    private javax.swing.JLabel jLabelHijAdultCasa;
    private javax.swing.JLabel jLabelMuerQuiere;
    private javax.swing.JLabel jLabelMuerteMadre;
    private javax.swing.JLabel jLabelNoCasada;
    private javax.swing.JLabel jLabelNoMHijos;
    private javax.swing.JLabel jLabelNumHijos;
    private javax.swing.JLabel jLabelParaQuiTrA;
    private javax.swing.JLabel jLabelRelaHomose;
    private javax.swing.JLabel jLabelRelacionesFueraMatr;
    private javax.swing.JLabel jLabelRelig;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelSexoFueraMatr;
    private javax.swing.JLabel jLabelViolacion;
    private javax.swing.JLabel jLabelViudoAlgVez;
    private javax.swing.JLabel jLabeldefecbeb;
    private javax.swing.JLabel jLabelgENERO;
    private javax.swing.JLabel jLabelimportantrabajo;
    private javax.swing.JLabel jLabellastyeartiempoCompl;
    private javax.swing.JLabel jLabelricoNotraba;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel jlabelApreciacionporlosHijos;
    private javax.swing.JLabel jlabelRazonDeAborto;
    // End of variables declaration//GEN-END:variables
}
